apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.28.1.211-10.28.1.215
      - 10.28.3.241-10.28.3.246
      - 10.28.3.236-10.28.3.240